name: fetch current courses

on:
  push:
    branches:
      - 蹦蹦
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  FetchCurrent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        department: [0, 1, 2]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
      - name: Install npm packages
        run: npm ci
      - name: fetch course data
        run: node fetchCourse.js ${{ matrix.department }}
      - uses: actions/upload-artifact@v4
        with:
          name: course-${{ matrix.department }}
          path: ./dist/
          retention-days: 2
  FetchSyllabus:
    needs: FetchCurrent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        department: [0, 1, 2]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
      - name: Install npm packages
        run: npm ci
      - name: get artifact
        uses: actions/download-artifact@v5
        with:
          name: course-${{ matrix.department }}
          path: ./dist/
          merge-multiple: true
      - name: fetch course data
        run: node fetchSyllabus.js ${{ matrix.department }}
      - uses: actions/upload-artifact@v4
        with:
          name: syllabus-${{ matrix.department }}
          path: ./dist/
          retention-days: 2
  Deploy:
    needs: [FetchCurrent, FetchSyllabus]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v5
        with:
          pattern: syllabus-*
          path: ./dist/
          merge-multiple: true
      - name: Show All years
        run: ls -R
        working-directory: ./dist/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          keep_files: true
